---

title: ML-Lee Predict PM2.5

---

In [1]:
import numpy as np
import pandas as pd
import scipy 

In [2]:
!ls
%reload_ext autoreload
%autoreload 2
%matplotlib inline

Homework1_introduction.txt sampleSubmission.csv
Prediction_PM2.5.ipynb     test(1).csv
Task-3.ipynb               train.csv
answer.csv                 ~$mework1_introduction.txt
fastai.ipynb


In [3]:
train = pd.read_csv('train.csv')
print(train[:20])

        Date stations observation     0     1     2     3     4     5     6  \
0   2014/1/1  station    AMB_TEMP    14    14    14    13    12    12    12   
1   2014/1/1  station         CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   
2   2014/1/1  station          CO  0.51  0.41  0.39  0.37  0.35   0.3  0.37   
3   2014/1/1  station        NMHC   0.2  0.15  0.13  0.12  0.11  0.06   0.1   
4   2014/1/1  station          NO   0.9   0.6   0.5   1.7   1.8   1.5   1.9   
5   2014/1/1  station         NO2    16   9.2   8.2   6.9   6.8   3.8   6.9   
6   2014/1/1  station         NOx    17   9.8   8.7   8.6   8.5   5.3   8.8   
7   2014/1/1  station          O3    16    30    27    23    24    28    24   
8   2014/1/1  station        PM10    56    50    48    35    25    12     4   
9   2014/1/1  station       PM2.5    26    39    36    35    31    28    25   
10  2014/1/1  station    RAINFALL    NR    NR    NR    NR    NR    NR    NR   
11  2014/1/1  station          RH    77    68    67 

In [4]:
df = train.loc[train['observation'] == 'PM2.5']
df.head()

Date stations observation   0   1   2   3   4   5   6 ...  14  15  16  \
9   2014/1/1  station       PM2.5  26  39  36  35  31  28  25 ...  36  45  42   
27  2014/1/2  station       PM2.5  21  23  30  30  22  18  13 ...  53  43  43   
45  2014/1/3  station       PM2.5  19  25  27  20  16  14  15 ...  32  36  34   
63  2014/1/4  station       PM2.5  27  27  14  20  22  24  26 ...  62  55  56   
81  2014/1/5  station       PM2.5  80  80  76  81  75  66  70 ...  64  73  57   

    17  18  19  20  21  22  23  
9   49  45  44  41  30  24  13  
27  45  46  32  16  19  22  26  
45  45  40  41  23  29  23  37  
63  67  78  83  90  75  85  82  
81  57  53  70  70  60  68  66  

[5 rows x 27 columns]

In [5]:
train.loc[0:3,'0':]

0     1     2     3     4     5     6     7     8     9  ...     14  \
0    14    14    14    13    12    12    12    12    15    17  ...     22   
1   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...    1.8   
2  0.51  0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78  0.74  ...   0.37   
3   0.2  0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26  0.23  ...    0.1   

     15    16    17    18    19    20    21    22    23  
0    22    21    19    17    16    15    15    15    15  
1   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  

[4 rows x 24 columns]

In [6]:
train_data = df.loc[:,'0':]
# could be replaced by
# train_data = df.iloc[:,3:]
train_data[:10]

0   1   2   3   4   5   6   7   8   9 ...  14  15  16  17  18  19  20  \
9    26  39  36  35  31  28  25  20  19  30 ...  36  45  42  49  45  44  41   
27   21  23  30  30  22  18  13  13  11  22 ...  53  43  43  45  46  32  16   
45   19  25  27  20  16  14  15   8   4   9 ...  32  36  34  45  40  41  23   
63   27  27  14  20  22  24  26  33  48  50 ...  62  55  56  67  78  83  90   
81   80  80  76  81  75  66  70  65  66  57 ...  64  73  57  57  53  70  70   
99   66  55  46  46  46  42  35  35  40  45 ...  62  59  61  50  60  62  62   
117  41  32  35  31  33  25  36  28  33  29 ...  62  61  47  54  57  59  61   
135  48  53  60  60  52  47  45  50  43  40 ...  35  36  36  32  33  33  34   
153  18  15   9   9  14  15  20  16  23  16 ...  20  20  20  18  18  22  15   
171   6   7   7   0   0   1   1   7   7   8 ...  23  20  18  15  16  10   6   

     21  22  23  
9    30  24  13  
27   19  22  26  
45   29  23  37  
63   75  85  82  
81   60  68  66  
99   50  45  43  
117  43  39  38  
135  21  15  13  
153  11   1   1  
171  11  22  28  

[10 rows x 24 columns]

In [7]:
train_x = []
train_y = []

for i in range(15):
    x = train_data.iloc[:,i:i+9]
    x.columns=np.array(range(9)) # if we not set the cloumns name, it will have diff cloumns name in every iteration
    y = train_data.iloc[:,i+9]
    y.cloumns = np.array(range(1)) 
    train_x.append(x)
    train_y.append(y)

#   train_y.append(y)

In [8]:
# train_x[:10]

In [9]:
train_x = pd.concat(train_x)
train_y = pd.concat(train_y)
# print(train_y)

In [10]:
train_x.iloc[:10,:]

0   1   2   3   4   5   6   7   8
9    26  39  36  35  31  28  25  20  19
27   21  23  30  30  22  18  13  13  11
45   19  25  27  20  16  14  15   8   4
63   27  27  14  20  22  24  26  33  48
81   80  80  76  81  75  66  70  65  66
99   66  55  46  46  46  42  35  35  40
117  41  32  35  31  33  25  36  28  33
135  48  53  60  60  52  47  45  50  43
153  18  15   9   9  14  15  20  16  23
171   6   7   7   0   0   1   1   7   7

In [11]:
train_y.iloc[:10]

9      30
27     22
45      9
63     50
81     57
99     45
117    29
135    40
153    16
171     8
dtype: object

In [12]:
train_x = np.array(train_x,float)
train_y = np.array(train_y,float)
train_x.shape
train_x = np.concatenate((np.ones((train_x.shape[0],1)), train_x), axis = 1)
train_x

array([[ 1., 26., 39., ..., 25., 20., 19.],
       [ 1., 21., 23., ..., 13., 13., 11.],
       [ 1., 19., 25., ..., 15.,  8.,  4.],
       ...,
       [ 1., 31., 31., ..., 39., 36., 24.],
       [ 1., 21., 21., ..., 11.,  0.,  7.],
       [ 1.,  1.,  7., ..., 28., 17., 24.]])

1. dimisions should be same, notice the dimesions of np.array(range(10)) is one
2. axis = 1 -> add to column ; default add to row 

In [13]:
#example
tmp = np.array(np.random.random((10,1)))

num = np.concatenate((np.ones((10,1)), tmp),axis = 1)

num

array([[1.        , 0.4947947 ],
       [1.        , 0.97839321],
       [1.        , 0.76541103],
       [1.        , 0.8693689 ],
       [1.        , 0.44862658],
       [1.        , 0.21099672],
       [1.        , 0.39010147],
       [1.        , 0.37070494],
       [1.        , 0.28694425],
       [1.        , 0.98761136]])

1. $y = X * w + b$
2. loss = $\frac{1}{2}((y-\hat{y})^2)$
3. $$ \frac{dy}{dw_i} = (y - \hat{y})*x_i $$

In [14]:
w = np.random.random(train_x.shape[1])
# w = np.zeros(len())
lr = 1e-1
epoches = 10000
sum_gra = np.zeros(train_x.shape[1])
for i in range(epoches):
    y_hat = np.dot(train_x,w)
#     loss = 1./2 * ( y_hat - train_y) ** 2
    loss = y_hat - train_y
    gra = 2*np.dot(train_x.transpose(),loss)
#     print(train_x.shape, gra.shape,loss.shape,y_hat.shape,train_y.shape)
    sum_gra += gra**2
    ada = np.sqrt(sum_gra)
    w -= lr * gra / ada

In [15]:
df = pd.read_csv('test(1).csv')
df.head()

id_0 AMB_TEMP    15    14  14.1    13  13.1  13.2  13.3  13.4    12
0  id_0      CH4   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8
1  id_0       CO  0.36  0.35  0.34  0.33  0.33  0.34  0.34  0.37  0.42
2  id_0     NMHC  0.11  0.09  0.09   0.1   0.1   0.1   0.1  0.11  0.12
3  id_0       NO   0.6   0.4   0.3   0.3   0.3   0.7   0.8   0.8   0.9
4  id_0      NO2   9.3   7.1   6.1   5.7   5.5   5.3   5.5   7.1   7.5

In [16]:
df = df.loc[df['AMB_TEMP'] == 'PM2.5']
df.head()

id_0 AMB_TEMP  15  14 14.1  13 13.1 13.2 13.3 13.4  12
8   id_0    PM2.5  27  13   24  29   41   30   29   27  28
26  id_1    PM2.5  46  47   57  78   84   76   59   61  61
44  id_2    PM2.5  10  10   25  34   40   39   36   25  22
62  id_3    PM2.5  71  58   51  41   41   46   43   34  29
80  id_4    PM2.5  13  23   18  10    5    5   13    9  12

In [17]:
df = df.iloc[:,2:]
df.head()

15  14 14.1  13 13.1 13.2 13.3 13.4  12
8   27  13   24  29   41   30   29   27  28
26  46  47   57  78   84   76   59   61  61
44  10  10   25  34   40   39   36   25  22
62  71  58   51  41   41   46   43   34  29
80  13  23   18  10    5    5   13    9  12

In [18]:
test_data = np.array(df,float)
test_data[:10]

array([[27., 13., 24., 29., 41., 30., 29., 27., 28.],
       [46., 47., 57., 78., 84., 76., 59., 61., 61.],
       [10., 10., 25., 34., 40., 39., 36., 25., 22.],
       [71., 58., 51., 41., 41., 46., 43., 34., 29.],
       [13., 23., 18., 10.,  5.,  5., 13.,  9., 12.],
       [25., 32., 40., 40., 31., 27., 13., 24., 29.],
       [37., 42., 65., 70., 71., 58., 51., 41., 41.],
       [17., 22., 17.,  9., 17., 23., 29., 17., 18.],
       [78., 84., 76., 59., 61., 61., 60., 49., 49.],
       [13., 13., 18., 20., 14.,  9., 16., 22., 35.]])

In [19]:
test_data = np.concatenate((np.ones((test_data.shape[0],1)),test_data),axis=1)
test_data[:10]

array([[ 1., 27., 13., 24., 29., 41., 30., 29., 27., 28.],
       [ 1., 46., 47., 57., 78., 84., 76., 59., 61., 61.],
       [ 1., 10., 10., 25., 34., 40., 39., 36., 25., 22.],
       [ 1., 71., 58., 51., 41., 41., 46., 43., 34., 29.],
       [ 1., 13., 23., 18., 10.,  5.,  5., 13.,  9., 12.],
       [ 1., 25., 32., 40., 40., 31., 27., 13., 24., 29.],
       [ 1., 37., 42., 65., 70., 71., 58., 51., 41., 41.],
       [ 1., 17., 22., 17.,  9., 17., 23., 29., 17., 18.],
       [ 1., 78., 84., 76., 59., 61., 61., 60., 49., 49.],
       [ 1., 13., 13., 18., 20., 14.,  9., 16., 22., 35.]])

In [20]:
w

array([ 1.98096581,  0.03311344, -0.04301065,  0.10669526, -0.08910889,
       -0.06752417,  0.37011385, -0.43398501, -0.02342711,  1.07467164])

In [21]:
y_pred = np.dot(test_data,w)
y_pred[:10]

array([27.50005224, 61.59124387, 20.68678462, 29.58974352, 11.00798058,
       34.99716275, 39.73746364, 16.33447074, 47.7321878 , 34.53067635])

In [22]:
y_submit = pd.read_csv('sampleSubmission.csv')
# get value by .value auto identify numbers
y_submit.value = y_pred
y_submit.to_csv('sampleSubmission.csv')
y_ans = pd.read_csv('answer.csv')
y_ans.head()
y_temp = pd.merge(y_ans[:10],y_submit[:10],on = 'id')
y_temp

id  value_x  Unnamed: 0  Unnamed: 0.1    value_y
0  id_0       33           0             0  27.500052
1  id_1       60           1             1  61.591244
2  id_2       16           2             2  20.686785
3  id_3       33           3             3  29.589744
4  id_4        5           4             4  11.007981
5  id_5       41           5             5  34.997163
6  id_6       46           6             6  39.737464
7  id_7       25           7             7  16.334471
8  id_8       38           8             8  47.732188
9  id_9       26           9             9  34.530676

calculate the error with L1 function

In [23]:
error = abs(y_ans.value-y_submit.value).sum()/len(y_ans.value)
error

5.030048312365773